Repository SUGAM-ARORA/UniCollab, pull requests merged in 2024-05, with the labels that each got.

#46 [Bug] : button accessable fix
  src/Components/MainContainer.css
Labels: gssoc, level1

#52 Create greetings.yaml
  .github/workflows/greetings.yaml
Labels: gssoc, level1

#61 Changed Favicon.
  public/favicon.ico
Labels: gssoc, level1

#73 [FIX] Fixed Notification Icon Function & Added Dropdown Close Functionality
  src/Components/Container.css
  src/Components/TopContainer.js
Labels: gssoc, level2

#88 Added pull_request_template.md
  .github/pull_request_template.md
Labels: gssoc, level1

#94 [FIX] Implemented Settings Page from #84
  package-lock.json
  package.json
  src/App.js
  src/Components/Container.css
  src/Components/Container.js
  src/Components/Menu.js
  src/Components/Settings/Settings.css
  src/Components/Settings/SettingsPage.js
  yarn.lock
Labels: gssoc, level3

#95 created contribute.md file
  CONTRIBUTE.md
Labels: gssoc, level1

#98 Fixes issue #85: Adjust search bar visibility and appearance
  src/Components/Container.css
  src/Components/TopContainer.js
Labels: gssoc, level1

#112 FIXES Issue #104 (Hover Background Color Alignment Issue on 'Source Code' Button)
  src/Components/MainContainer.css
  src/index.css
Labels: gssoc, level1

#49 Assigning route to the icons in navbar Issue Number #24
  src/Components/Menu.js
Labels: gssoc, level1

#118 Auto comment on closed PR
  .github/workflows/comment-on-close.yaml
Labels: gssoc, level1

#119 Updated Logo functionality
  src/Components/Menu.css
  src/Components/Menu.js
  yarn.lock
Labels: gssoc, level1

#120 Add custom scrollbar styles for vertical and horizontal scrollbars issue #107
  src/index.css
Labels: gssoc, level1

#123 Animations Added
  package-lock.json
  src/App.css
  src/Components/MainContainer.js
  src/Components/MainRightBottomCard.js
  src/Components/MainRightTopCard.js
  src/Components/Menu.js
  src/Components/TopContainer.js
  yarn.lock
Labels: gssoc, level3

#134 [FIXES #106] Tooltips Icons
  src/Components/Menu.css
  src/Components/Menu.js
Labels: gssoc, level2

#136 Added the feature to auto comment on pr merged
  .github/workflows/auto-comment-on-pr-merge.yml
Labels: gssoc, level1

#145 added workflow for closing old PRs
  .github/workflows/close-old-pr.yml
Labels: gssoc

#148 [FIXES #138} Implemented Blog Page
  src/App.js
  src/Components/footer_section/BlogPage/BlogPage.css
  src/Components/footer_section/BlogPage/BlogPage.js
Labels: gssoc, level3

#155 added workflow as per issue #142
  .github/workflows/autocomment-iss-close.yml
Labels: gssoc

#154 Enhanced footer: Added Services section
  src/App.js
  src/Components/footer_section/about_us/About_us.css
  src/Components/footer_section/about_us/About_us.js
  src/Components/footer_section/services/Services.css
  src/Components/footer_section/services/Services.js
Labels: gssoc, level2

#168 Updation done
  README.md
  UniCollab-Bottom.png
  UniCollab-Top.png
  Unicollab.png
  gssoc-banner.png
Labels: gssoc, level2

#158 My feature branch
  src/Components/CardMain.js
  src/Components/MainContainer.js
Labels: gssoc, level1

#160 Footer logo added
  package-lock.json
  public/index.html
  src/Components/Footer.css
  src/Components/Footer.js
  yarn.lock
Labels: gssoc, level2

#163 FIXED #144 : Added a Contact Page
  src/App.js
  src/Components/footer_section/ContactUs/contact_us.css
  src/Components/footer_section/ContactUs/contact_us.js
Labels: gssoc, level2

#173 fixed the right and left panel
  src/Components/MainContainer.css
  yarn.lock
Labels: gssoc, level2

#167 adding services
  src/App.js
  src/Components/footer_section/about_us/About_us.css
  src/Components/footer_section/about_us/About_us.js
  src/Components/footer_section/services/Services.css
  src/Components/footer_section/services/Services.js
Labels: gssoc, level1

#179 FAQ Section Updated
  src/App.js
  src/Components/footer_section/FAQPage/FAQPage.css
  src/Components/footer_section/FAQPage/FAQPage.js
Labels: gssoc, level2
