Repository SUGAM-ARORA/UniCollab, pull requests merged in 2024-07, with the labels that each got.

#384 login and signup in frontend
  BACKEND/controllers/authcontrollers.js
  BACKEND/index.js
  BACKEND/package-lock.json
  BACKEND/package.json
  BACKEND/routes/auth.js
  src/Components/Login.js
  src/Components/TopContainer.js
  src/index.js
Labels: gssoc, level3

#388 border and box shadow
  src/Components/Careers/careers.css
  src/Components/footer_section/services/Services.css
Labels: gssoc, level2

#396 Update Menu.js
  src/Components/Menu.js
Labels: gssoc, level1

#408 Added:To The Top Button
  src/Components/CardMain.js
  yarn.lock
Labels: gssoc, level1

#409 recreate careers page
  src/Components/Careers/careers.css
Labels: gssoc, level1

#418 Made Contact Page Responsive
  src/Components/footer_section/ContactUs/contact_us.css
  src/Components/footer_section/ContactUs/contact_us.js
  yarn.lock
Labels: gssoc, level2

#426 Made Careers Page Responsive
  src/Components/Careers/CareersPage.js
  src/Components/Careers/careers.css
Labels: gssoc, level2

#420 Alignment Issue
  src/Components/Footer.js
  src/Components/FreeLancer/Freelancer.js
  src/Components/FreeLancer/homeicon.png
  src/Components/Menu.css
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level2

#428 Made Freelancer Page Responsive
  src/Components/FreeLancer/Freelancer.css
  yarn.lock
Labels: gssoc, level2

#427 Aligned the to-the-top button to center
  src/Components/CardMain.js
Labels: gssoc, level1

#431 Update the react-router-dom and Fix Footer , 2 issues completed
  src/App.js
  src/Components/Login.css
  src/configs/router.js
Labels: gssoc, level2

#436 Elevating User Experience: Footer Refinement, Freelancer Page Fixes, and FAQ Styling
  src/Components/Footer.css
  src/Components/Footer.js
  src/Components/FreeLancer/Freelancer.css
  src/Components/Login.css
  src/Components/Login.js
  src/Components/footer_section/FAQPage/FAQPage.css
Labels: gssoc, level2

#434 mkdocs site documentation
  .github/workflows/mkdocs.yaml
  mkdocs/docs/advantages.md
  mkdocs/docs/contributing.md
  mkdocs/docs/featuresandservices.md
  mkdocs/docs/futurescope.md
  mkdocs/docs/images/gssoc-banner.png
  mkdocs/docs/images/logo.png
  mkdocs/docs/index.md
  mkdocs/docs/installation.md
  mkdocs/docs/objectives.md
  mkdocs/docs/purpose.md
  mkdocs/docs/technologystack.md
  mkdocs/docs/usage.md
  mkdocs/mkdocs.yml
  mkdocs/requirements.txt
Labels: gssoc, level3

#438 UI Refinements: Adding Shadows and Aligning Login Page Elements
  src/Components/Login.css
  src/Components/Login.js
  src/Components/footer_section/BlogPage/BlogPage.css
Labels: gssoc, level2

#435 added scroll feature in top contributor
  src/Components/MainContainer.css
  src/Components/MainRightBottomCard.js
  src/Components/TopSeller.js
  yarn.lock
Labels: gssoc, level2

#446 Connect with The Chatbot
  package-lock.json
  package.json
  public/.eslintrc.js
  public/index.html
  src/App.js
  src/Components/ChatbotIcon.css
  src/Components/ChatbotIcon.js
  yarn.lock
Labels: gssoc, level3

#404 SEO tags added
  package-lock.json
  package.json
  src/App.js
  yarn.lock
Labels: gssoc, level2

#454 Added Scroll-to-Top Button #444
  package-lock.json
  package.json
  src/App.js
  src/Components/Footer.css
  src/Components/Footer.js
  src/Components/gototop.js
  yarn.lock
Labels: gssoc, level1

#450 Enhancement done in the statistics section.
  src/Components/MainContainer.css
Labels: gssoc, level1

#432 Added email pattern verification
  src/Components/footer_section/ContactUs/contact_us.js
Labels: gssoc, level1

#466 Added Navbar icons
  src/Components/Footer.js
  src/Components/TopContainer.js
Labels: gssoc, level1

#481 Added Hover Effects
  package-lock.json
  src/Components/FreeLancer/Freelancer.css
  yarn.lock
Labels: gssoc, level1

#451 Add Firebase google Login
  src/App.js
  src/Components/Login.js
  src/configs/firebase.js
Labels: gssoc, level3

#495 Proper Space given to Cards
  package-lock.json
  src/Components/MainContainer.css
Labels: gssoc, level3

#500 Making a Cart Page
  package-lock.json
  src/Components/Menu.js
  src/Components/Profiles.js
  src/Components/cart/App.js
  src/Components/cart/cart.css
  src/Components/cart/cart.js
  src/Components/cart/index.html
Labels: gssoc, level3

#416 Feat: News letter section added
  src/Components/Footer.js
  src/Components/footer_section/Mail/Mail.css
  src/Components/footer_section/Mail/SubscribeMail.js
Labels: gssoc, level1

#502 Github Login
  src/Components/Firebase/Firebase.js
  src/Components/Login.css
  src/Components/Login.js
Labels: gssoc, level3

#507 fix: hover effect
  src/Components/Footer.css
Labels: gssoc, level1

#512 Embed Firebase Auth Code for Handling User Authentication
  src/Components/Footer.css
  src/Components/Footer.js
  src/Components/Login.js
  src/Components/Menu.css
  src/Components/Menu.js
  src/Components/cart/App.js
  src/Components/cart/style.js
Labels: gssoc, level3

#484 Added scroll progress bar
  public/index.html
Labels: gssoc, level1

#520 FreeLancer Fixed
  src/Components/FreeLancer/Freelancer.css
  src/Components/FreeLancer/Freelancer.js
Labels: gssoc, level1

#521 Animation social#509
  src/Components/Footer.css
  src/Components/MainContainer.css
  src/Components/TopContainer.css
Labels: gssoc, level1

#524 Changed Position of Newsletter
  src/Components/Footer.js
  src/Components/footer_section/Mail/Mail.css
  src/Components/footer_section/Mail/SubscribeMail.js
  yarn.lock
Labels: gssoc, level2

#501 Footer unresponsive#477
  package-lock.json
  yarn.lock
Labels: gssoc, level1

#540 Improve Backend of Contact Page
  BACKEND/package-lock.json
  BACKEND/package.json
  BACKEND/server.js
  src/Components/footer_section/ContactUs/contact_us.css
  src/Components/footer_section/ContactUs/contact_us.js
Labels: gssoc, level2

#541 Connected Cart Page
  src/Components/cart/cart.js
  src/configs/router.js
Labels: gssoc, level2

#548 Adding Phone Number Authentication
  src/Components/Firebase/Firebase.js
  src/Components/Login.js
Labels: gssoc, level2

#543 Made Footer Responsive
  src/Components/footer_section/Mail/Mail.css
Labels: gssoc, level1

#549 Enhancing the Design of The 'Help Us Improve' Page
  src/Components/feedback/feedback.css
Labels: gssoc, level1

#551 Adding Facebook Authentication
  src/App.js
  src/Components/Firebase/Firebase.js
  src/Components/Login.css
  src/Components/Login.js
  src/Components/footer_section/Pricing/pricing.js
Labels: gssoc, level3

#535 Fix Overlapping of Feedback button and Scroll to top buttons
  src/Components/gototop.js
Labels: gssoc, level1

#556 Enchancing the Design and Styling of the Cart Page
  src/Components/Login.css
  src/Components/cart/12.png
  src/Components/cart/cart.css
  src/Components/cart/cart.js
  src/Components/cart/index.html
  src/Components/cart/style.js
  src/Components/footer_section/Pricing/pricing.js
Labels: gssoc, level3

#559 Adding Twitter Authentication
  src/Components/Firebase/Firebase.js
  src/Components/Login.js
Labels: gssoc, level2

#566 Update Footer.js
  src/Components/Footer.js
Labels: gssoc, level1

#557 change learn.md
  LEARN.md
Labels: gssoc, level1

#561 Adding Microsoft Authentication
  src/Components/Firebase/Firebase.js
  src/Components/Login.js
  src/Components/footer_section/ContactUs/contact_us.css
  src/Components/footer_section/ContactUs/contact_us.js
Labels: gssoc, level3

#562 Adding LinkedIn Authentication
  src/Components/Firebase/Firebase.js
  src/Components/Login.js
Labels: gssoc, level2

#569 Added Home Button
  package-lock.json
  src/Components/feedback/feedbackform.js
  src/Components/feedback/homeicon.png
Labels: gssoc, level1

#586 Implement Popular Page to Highlight Trending Content
  src/Components/CardMain.css
  src/Components/CardMain.js
  src/Components/MainContainer.js
  src/Components/Popular.css
  src/Components/Popular.js
Labels: gssoc, level2, priority : high

#553 made static navabr of top contributor
  src/Components/MainContainer.css
  yarn.lock
Labels: gssoc, level1

#591 Fixed Login and Signup Pages
  package-lock.json
  src/Components/Login.css
  yarn.lock
Labels: gssoc, level2

#595 Enhance the README File
  README.md
  UniCollab-Bottom.png
  UniCollab-Top.png
Labels: gssoc, level1

#596 Comprehensive Documentation Update
  mkdocs/docs/advantages.md
  mkdocs/docs/contributing.md
  mkdocs/docs/images/UniCollab-Bottom.png
  mkdocs/docs/images/UniCollab-Top.png
  mkdocs/docs/installation.md
  mkdocs/docs/technologystack.md
Labels: gssoc, level2

#578 Main page res#476
  package-lock.json
  src/Components/MainContainer.css
  src/Components/TopContainer.css
  yarn.lock
Labels: gssoc, level1

#609 Implementation of Speed Page
  src/Components/Menu.css
  src/Components/Menu.js
  src/Components/Stopwatch.css
  src/Components/Stopwatch.js
  src/Components/menu_section/my_projects/MyProjects.js
Labels: gssoc, level3

#611 Adding Home icon in the Settings Page
  src/Components/Settings/SettingsPage.js
Labels: gssoc, level1

#613 Added Hover Effects on Cards In Cart Page
  src/Components/cart/cart.js
Labels: gssoc, level1

#614 Fixed UI of Login and Sign-Up Page
  src/Components/Login.css
  src/Components/feedback/feedback.css
Labels: gssoc, level1

#592 Follow Button Fixed
  src/Components/MainRightBottomCard.js
Labels: gssoc, level1

#612 Removed Background color
  src/Components/MainContainer.css
Labels: gssoc, level1

#604 Implemented Rate-Us Page
  src/Components/Footer.js
  src/Components/RateUs.css
  src/Components/RateUs.js
Labels: gssoc, level2

#603 Made Sign-Out button Functional
  src/Components/Menu.css
  src/Components/Menu.js
  src/Components/TopContainer.css
Labels: gssoc, level2

#620 Expandable Sidebar with Toggle Button
  src/Components/Login.css
  src/Components/Login.js
  src/Components/Menu.css
  src/Components/Menu.js
  src/Components/TopContainer.css
  src/Components/menu_section/my_projects/MyProjects.css
Labels: gssoc, level3

#618 Fixed overlap issue of the sidebar and dropdown menu
  package-lock.json
  src/Components/Menu.js
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level2

#622 Sidebar Page Overlapping
  src/Components/Menu.css
  src/Components/Menu.js
  src/Components/Popular.js
  src/Components/TopContainer.css
Labels: gssoc, level2

#624 Making of Sort By Buttons
  src/Components/MainContainer.css
  src/Components/MainContainer.js
  src/Components/TopContainer.css
Labels: gssoc, level2

#626 Enhance Search Functionality and Update Project Listing
  src/Components/TopContainer.js
  src/Components/searchResults.js
  src/configs/router.js
Labels: gssoc, level2

#634 added x to twitter logo
  src/Components/Footer.js
Labels: gssoc, level1

#631 Settings Page Config
  BACKEND/package-lock.json
  BACKEND/server.js
  package-lock.json
  package.json
  src/Components/Settings/SettingsPage.js
Labels: gssoc, level2

#625 Format and Enhance Legal Pages: Privacy Policy, Terms and Condition, Licensing
  src/Components/footer_section/Legal/Licensing.js
  src/Components/footer_section/Legal/PrivacyPolicy.js
  src/Components/footer_section/Legal/TermsandConditions.js
Labels: gssoc, level2

#639 Setting the UI of Main Page
  src/Components/MainRightTopCard.css
  src/Components/MainRightTopCard.js
  src/Components/Menu.js
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level2
