Repository SUGAM-ARORA/UniCollab, pull requests merged in 2024-06, with the labels that each got.

#189 Made several changes and fixed navbar responsiveness.
  src/Components/Container.css
  src/Components/Menu.css
  src/Components/Menu.js
  src/Components/TopContainer.js
Labels: gssoc, level3

#218 Added About Page
  src/Components/footer_section/about_us/About_us.css
  src/Components/footer_section/about_us/About_us.js
  src/Components/footer_section/about_us/About_us.jsx
  src/img/collaboration.png
  src/img/collaborationhover.png
  src/img/event.png
  src/img/eventhover.png
  src/img/knowledge.png
  src/img/knowledgehover.png
  src/img/project.png
  src/img/projecthover.png
Labels: gssoc, level3

#186 Add My Projects and New Project pages
  src/App.js
  src/Components/Menu.js
  src/Components/menu_section/my_projects/MyProjects.css
  src/Components/menu_section/my_projects/MyProjects.js
  src/Components/menu_section/new_project/NewProject.css
  src/Components/menu_section/new_project/NewProject.js
Labels: gssoc, level2

#207 Fixes #190 : Added Premium Features Option
  src/App.js
  src/Components/Footer.css
  src/Components/Footer.js
  src/Components/footer_section/Pricing/pricing.css
  src/Components/footer_section/Pricing/pricing.js
Labels: gssoc, level3

#223 Updated Footer
  package-lock.json
  package.json
  src/Components/Footer.css
  src/Components/Footer.js
  src/Components/TopContainer.js
  yarn.lock
Labels: gssoc, level3

#226 added error 404 page
  src/App.js
  src/Components/404_page/404.json
  src/Components/404_page/Error.css
  src/Components/404_page/Error.js
Labels: gssoc, level2

#203 Feature Added : Implemented Responsive "Read More" Button with Dynamic Project Details #181
  src/App.js
  src/Components/CardMain.js
  src/Components/MainContainer.css
  src/Components/MainContainer.js
  src/Components/Readmore.css
  src/Components/Readmore.js
  src/Components/projects/arrow.png
  src/Components/projects/card1.jpg
  src/Components/projects/card2.jpg
  src/Components/projects/card3.jpg
  src/Components/projects/card4.jpg
  src/Components/projects/card5.jpg
  src/Components/projects/card6.jpg
  src/Components/projects/index.js
Labels: gssoc, level2

#229 5 star rating page added
  src/img/review.css
  src/img/review.html
Labels: gssoc, level1

#244 done#201
  src/Components/Container.css
  src/Components/TopContainer.js
Labels: gssoc, level2

#249 add dockerfile and dockerignore
  .dockerignore
  Dockerfile
Labels: gssoc, level2

#252 Adding 6 more projects to the feed wrt #191
  src/Components/projects/card10.png
  src/Components/projects/card11.png
  src/Components/projects/card12.png
  src/Components/projects/card7.png
  src/Components/projects/card8.png
  src/Components/projects/card9.png
  src/Components/projects/index.js
Labels: gssoc, level3

#256 navbar added on top
  package-lock.json
  package.json
  src/Components/Container.css
  src/Components/TopContainer.css
  src/Components/TopContainer.js
  yarn.lock
Labels: gssoc, level2

#260 Login Page created
  package-lock.json
  package.json
  public/1.png
  public/2.png
  src/App.js
  src/Components/CreateAccount.css
  src/Components/CreateAccount.js
  src/Components/Footer.css
  src/Components/Login.css
  src/Components/Login.js
  src/Components/TopContainer.css
  src/Components/TopContainer.js
  yarn.lock
Labels: gssoc, level3

#273 form validation
  form/index.html
  form/script.js
  form/styles.css
Labels: gssoc, level1

#277 Login Page updated
  src/Components/CreateAccount.css
  src/Components/Login.css
  src/Components/Login.js
Labels: gssoc, level2

#282 Added Legal Pages
  package-lock.json
  package.json
  src/App.js
  src/Components/CreateAccount.css
  src/Components/Footer.js
  src/Components/Login.css
  src/Components/footer_section/Legal/Licensing.js
  src/Components/footer_section/Legal/PrivacyPolicy.js
  src/Components/footer_section/Legal/TermsandConditions.js
  yarn.lock
Labels: gssoc, level3

#286 Fixes #217 : Added a Profile Page
  package-lock.json
  package.json
  src/App.js
  src/Components/Profile/Avatar.png
  src/Components/Profile/instagram.png
  src/Components/Profile/linkedin.png
  src/Components/Profile/location.png
  src/Components/Profile/profile.css
  src/Components/Profile/profile.js
  src/Components/menu_section/my_projects/MyProjects.js
  yarn.lock
Labels: gssoc, level3

#303 Adding a box-shadow on the div
  src/Components/footer_section/about_us/About_us.css
Labels: gssoc, level1

#289 feat: added issue btns and respective forms
  .github/ISSUE_TEMPLATE/bug.yml
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/custom.md
  .github/ISSUE_TEMPLATE/documentation.yml
  .github/ISSUE_TEMPLATE/feature.yml
  .github/ISSUE_TEMPLATE/feature_request.md
Labels: gssoc, level1

#230 Random Developer Names with Profile Pages #204
  src/App.js
  src/Components/CardMain.js
  src/Components/Profile.css
  src/Components/Profiles.js
  src/Components/Readmore.css
  src/Components/Readmore.js
  src/Components/projects/index.js
  src/Components/projects/profile.png
  src/Components/projects/profile1.png
Labels: gssoc, level2

#308 Resolved Alignment Issue
  package-lock.json
  src/Components/MainContainer.css
  src/Components/MainContainer.js
  yarn.lock
Labels: gssoc, level2

#323 Links Updated
  .vscode/launch.json
  package-lock.json
  package.json
  public/1.png
  src/Components/CreateAccount.css
  src/Components/CreateAccount.js
  src/Components/Footer.css
  src/Components/Footer.js
  src/Components/TopContainer.css
  src/Components/TopContainer.js
  src/Components/footer_section/Legal/Licensing.js
  src/Components/footer_section/Legal/PrivacyPolicy.js
  src/Components/footer_section/Legal/TermsandConditions.js
  yarn.lock
Labels: gssoc, level3

#311 Added "Licensing" Page Reflecting "MIT Licence"
  src/Components/footer_section/Legal/Licensing.js
Labels: gssoc, level1

#291 back navigation button added to pricing page #227
  src/Components/Readmore.js
  src/Components/footer_section/Pricing/pricing.css
  src/Components/footer_section/Pricing/pricing.js
Labels: gssoc, level2

#322 color coordination issue
  form/index.html
  form/styles.css
  src/Components/footer_section/about_us/About_us.css
  src/Components/menu_section/my_projects/MyProjects.css
Labels: gssoc, level2

#333 add kubernetes into this
  deployment-app.yml
  service-app.yml
Labels: gssoc, level3

#326 home button added to all pages
  src/Components/footer_section/BlogPage/BlogPage.css
  src/Components/footer_section/BlogPage/BlogPage.js
  src/Components/footer_section/ContactUs/contact_us.css
  src/Components/footer_section/ContactUs/contact_us.js
  src/Components/footer_section/FAQPage/FAQPage.css
  src/Components/footer_section/FAQPage/FAQPage.js
  src/Components/footer_section/about_us/About_us.css
  src/Components/footer_section/about_us/About_us.jsx
  src/Components/footer_section/services/Services.css
  src/Components/footer_section/services/Services.js
  src/img/homeicon.png
  src/img/homeicon1.png
Labels: gssoc, level2

#331 Initial backed
  BACKEND/.gitignore
  BACKEND/README.md
  BACKEND/index.js
  BACKEND/middleware/auth.js
  BACKEND/models/user.js
  BACKEND/package-lock.json
  BACKEND/package.json
  BACKEND/routes/auth.js
Labels: gssoc, level2

#337 notification on sumbit button
  package-lock.json
  package.json
  src/Components/footer_section/ContactUs/contact_us.js
  yarn.lock
Labels: gssoc, level2

#339 Added styles to "Vertical Scroll Bar" Matching to the Website Theme
  src/index.css
Labels: gssoc, level1

#342 Connect Your Journey
  package-lock.json
  package.json
  src/App.css
  src/App.js
  src/Components/CreateAccount.css
  src/Components/CreateAccount.js
  src/Components/Footer.css
  src/Components/Login.css
  src/Components/Login.js
  src/Components/Profile/log.svg
  src/Components/Profile/register.svg
  src/Components/TopContainer.js
  yarn.lock
Labels: gssoc, level3

#353 Create Your Journey Updated
  package-lock.json
  package.json
  src/App.js
  src/Components/Login.css
  src/Components/Login.js
  src/Components/footer_section/ContactUs/contact_us.js
  yarn.lock
Labels: gssoc, level3

#354 Footer Icon working set
  src/Components/CardMain.js
  src/Components/Footer.css
  src/Components/Login.css
  src/Components/MainRightBottomCard.js
  src/Components/TopContainer.js
Labels: gssoc, level2

#344 Fixes #302 : Added Careers Page
  src/App.js
  src/Components/Careers/CareersPage.js
  src/Components/Careers/careers.css
Labels: gssoc, level3

#356 change the folder structure
  BACKEND/controllers/authcontrollers.js
  BACKEND/routes/auth.js
Labels: gssoc, level1

#357 Enhancement done in the Contact page.
  src/Components/footer_section/ContactUs/contact_us.css
  src/Components/footer_section/ContactUs/contact_us.js
Labels: gssoc, level2

#363 Cursor Enhancement
  form/index.html
  public/index.html
  src/index.js
Labels: gssoc, level2

#367 made the view more button working
  src/Components/MainRightBottomCard.js
  src/Components/MainRightTopCard.js
Labels: gssoc, level2

#376 Add reset password feature while login
  src/App.js
  src/Components/Login.css
  src/Components/Login.js
  src/Components/auth/resetPassword/EmailVerification.js
  src/Components/auth/resetPassword/OTPVerification.js
  src/Components/auth/resetPassword/ResetPassword.js
  src/Components/auth/resetPassword/resetPassword.css
Labels: gssoc, level2

#379 Adding Multilingual Facility
  form/index.html
  package-lock.json
  package.json
  public/index.html
  src/Components/Login.css
  src/Components/Login.js
  yarn.lock
Labels: gssoc, level2

#369 Add "Back To Home Button" in "Legal and Missing" Pages
  src/Components/Careers/CareersPage.js
  src/Components/footer_section/Legal/Licensing.js
  src/Components/footer_section/Legal/PrivacyPolicy.js
  src/Components/footer_section/Legal/TermsandConditions.js
Labels: gssoc, level1

#393 fixed New project page display issue
  src/Components/menu_section/new_project/NewProject.css
  src/Components/menu_section/new_project/NewProject.js
Labels: gssoc, level1

#400 Added "Hire A Freelancer" Page
  src/App.js
  src/Components/FreeLancer/Avatar.png
  src/Components/FreeLancer/Freelancer.css
  src/Components/FreeLancer/Freelancer.js
  src/Components/FreeLancer/HirePage.webp
  src/Components/FreeLancer/eighth.webp
  src/Components/FreeLancer/fifth.webp
  src/Components/FreeLancer/fourth.webp
  src/Components/FreeLancer/hire-landing-cat-branding.webp
  src/Components/FreeLancer/hire-landing-cat-logo-design.webp
  src/Components/FreeLancer/location.png
  src/Components/FreeLancer/seventh.webp
  src/Components/FreeLancer/sixth.webp
  src/Components/FreeLancer/third.webp
  src/Components/TopContainer.js
Labels: gssoc, level3

#397 Made login page responsive for all devices
  src/Components/Login.css
  src/Components/Login.js
Labels: gssoc, level1

#392 Fix "Cursor-Trail" Effect "Synchronization" Issue
  public/index.html
  src/App.css
  src/Components/Container.css
  src/Components/Footer.css
  src/Components/TopContainer.css
  src/index.js
Labels: gssoc, level2

#382 Fixed the footer sizing for all sizes to look uniform
  src/Components/TopContainer.css
Labels: gssoc, level1
