Repository SUGAM-ARORA/UniCollab, pull requests merged in 2024-08, with the labels that each got.

#643 Created Our Contributors Page for Unicollab
  package-lock.json
  src/Components/Contributors.css
  src/Components/Contributors.js
  src/Components/Footer.js
  src/configs/router.js
Labels: gssoc, level2

#647 Testimonials Creation
  src/App.js
  src/Components/Footer.js
  src/Components/Testimonials/Testimonials.css
  src/Components/Testimonials/Testimonials.jsx
  src/configs/router.js
Labels: gssoc, level2

#656 Implementing Delicious Page
  src/Components/Delicious/Delicious.css
  src/Components/Delicious/Delicious.js
  src/Components/Menu.js
  src/configs/router.js
Labels: gssoc, level3

#652 Added Wallet Page
  src/Components/Menu.js
  src/Components/footer_section/Pricing/pricing.css
  src/Components/wallet/Wallet.css
  src/Components/wallet/Wallet.js
  src/configs/router.js
Labels: gssoc, level3

#657 Trending Now Page
  src/Components/Menu.js
  src/Components/Trending/Trending.css
  src/Components/Trending/Trending.js
  src/configs/router.js
Labels: gssoc, level3

#659 Fix/left sidebar responsiveness and right bar icon responsiveness and overlapping
  .idea/.gitignore
  .idea/UniCollab.iml
  .idea/modules.xml
  .idea/vcs.xml
  package-lock.json
  package.json
  src/Components/Profile/log.svg
  src/Components/RateUs.css
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level2

#668 Rate Us Backend
  BACKEND/server.js
  src/Components/Contributors.css
  src/Components/Contributors.js
  src/Components/RateUs.js
Labels: gssoc, level2

#669 Search Icon Position
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level2

#671 Reset Password Page
  src/App.js
  src/Components/Login.js
  src/Components/forgot.css
  src/Components/forgot.js
  src/configs/router.js
Labels: gssoc, level2

#673 Forgot Backend
  BACKEND/Express.js
  src/Components/MainRightBottomCard.js
  src/Components/Settings/Settings.css
  src/Components/forgot.js
Labels: gssoc, level2

#680 Type Of Projects
  src/Components/CardMain.css
  src/Components/CardMain.js
  src/Components/Readmore.js
  src/Components/projects/index.js
Labels: gssoc, level2

#689 Created a responsive hamburger menu , added animation to it , fixed width , added cross button
  src/Components/Container.css
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level1

#691 Created a Completely Responsive Carreers Page
  src/Components/Careers/CareersPage.js
  src/Components/Careers/careers.css
Labels: gssoc, level2

#697 Made needed changes and fixed components alignment
  src/App.css
  src/App.js
  src/Components/CardMain.css
  src/Components/CardMain.js
  src/Components/ChatbotIcon.css
  src/Components/Footer.js
  src/Components/MainContainer.js
  src/Components/Menu.js
  src/Components/TopContainer.css
Labels: gssoc, level3

#700 Feat/light and dark toggle
  src/App.js
  src/Components/CardMain.js
  src/Components/Careers/CareersPage.js
  src/Components/Careers/careers.css
  src/Components/Container.js
  src/Components/Delicious/Delicious.css
  src/Components/Delicious/Delicious.js
  src/Components/Footer.css
  src/Components/Footer.js
  src/Components/FreeLancer/Freelancer.css
  src/Components/FreeLancer/Freelancer.js
  src/Components/Login.js
  src/Components/MainContainer.css
  src/Components/MainContainer.js
  src/Components/MainRightBottomCard.js
  src/Components/MainRightTopCard.css
  src/Components/MainRightTopCard.js
  src/Components/Menu.css
  src/Components/Menu.js
  src/Components/RateUs.css
  src/Components/RateUs.js
  src/Components/Readmore.css
  src/Components/Readmore.js
  src/Components/Settings/Settings.css
  src/Components/Settings/SettingsPage.js
  src/Components/TopContainer.css
  src/Components/TopContainer.js
  src/Components/Trending/Trending.css
  src/Components/Trending/Trending.js
  src/Components/cart/cart.css
  src/Components/cart/cart.js
  src/Components/feedback/feedback.css
  src/Components/feedback/feedbackform.js
  src/Components/footer_section/BlogPage/BlogPage.css
  src/Components/footer_section/BlogPage/BlogPage.js
  src/Components/footer_section/ContactUs/contact_us.css
  src/Components/footer_section/ContactUs/contact_us.js
  src/Components/footer_section/FAQPage/FAQPage.css
  src/Components/footer_section/FAQPage/FAQPage.js
  src/Components/footer_section/Mail/Mail.css
  src/Components/footer_section/Pricing/pricing.css
  src/Components/footer_section/Pricing/pricing.js
  src/Components/footer_section/about_us/About_us.css
  src/Components/footer_section/about_us/About_us.jsx
  src/Components/footer_section/services/Services.css
  src/Components/footer_section/services/Services.js
  src/Components/menu_section/my_projects/MyProjects.css
  src/Components/menu_section/my_projects/MyProjects.js
  src/Components/wallet/Wallet.js
  src/index.css
Labels: gssoc, level3

#710 Fixed popular section cards
  src/Components/CardMain.js
  src/Components/Cardcontainer.js
  src/Components/Popular.js
Labels: gssoc, level2

#712 Improve features on search results
  src/Components/TopContainer.css
  src/Components/TopContainer.js
  src/Components/searchResults.js
Labels: gssoc, level2

#704 Fixed Gap between navbar elements
  src/Components/Footer.css
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level1

#719 Navbar Problem
  src/Components/CardMain.js
  src/Components/Popular.css
  src/Components/Popular.js
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level2

#722 Different Colours Icons Naving
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level1

#726 Fixed navbar for mobile screen
  src/Components/TopContainer.css
  src/Components/TopContainer.js
Labels: gssoc, level1

#728 Added Weatherly Project
  src/Components/CardMain.js
  src/Components/projects/card6.jpg
  src/Components/projects/index.js
  src/Projects/WeatherLy/index.html
  src/Projects/WeatherLy/scenery.jpg
  src/Projects/WeatherLy/script.js
  src/Projects/WeatherLy/style.css
  src/img/card6.jpg
Labels: gssoc, level3
